### ISSUE TITLE
autoplayer hits ink and shadow death notes

### ISSUE THREAD

**Issue by Skeleton19** [wally-rblx/funky-friday-autoplay#48]
On the song Last Reel it happens.

https://user-images.githubusercontent.com/50092873/164644288-afe19cf0-5e99-4b8d-a580-6a1604773f62.mp4

**Comment by Skeleton19** [comment]
I used Synapse X.

**Comment by HapJim** [comment]
found a fix.
replace this line:
local ignoredNoteTypes = { Death = true, ['Pea Note'] = true }

with this line:
local ignoredNoteTypes = { Death = true, Poison = true, Mechanic = true }

however, those notes on last reel seem way too close to the normal notes. i cant get it to not hit the death notes because of how big the hitbox is

**Comment by wally-rblx** [comment]
> 

you can add Poison to the table without overwriting the Pea Note thing lol

**Comment by wally-rblx** [comment]
@HapJim you can add new keys to the table without overwriting them
@Skeleton19 i will fix this later most likely, thanks for reporting

**Comment by wally-rblx** [comment]
fixed
